In [1]:
import numpy as np

In [3]:
board = np.array([
    [-0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5],
    [-0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5],
    [-0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5],
    [-0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5],
    [-0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5],
    [ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0],
    [ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1.0,  1.0,  1.0],
    [ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1.0, -0.5,  1.0],
    [ 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1.0,  1.0,  1.0],
], dtype=float)


In [24]:
def solve(current_board):
    # Add a 1-cell border filled with 10
    padded = np.pad(current_board, pad_width=((1, 1), (1, 1)),
                    mode='constant', constant_values=10)

    H, W = padded.shape
    # Number of valid 3×3 regions (excluding the border centers)
    num_regions = (H - 2) * (W - 2)

    extract_board = np.zeros((3, 3, num_regions))

    idx = 0
    for i in range(1, H - 1): 
        for j in range(1, W - 1):
            region = padded[i-1:i+2, j-1:j+2]
            extract_board[:, :, idx] = region
            idx += 1

    return extract_board


In [26]:
extract = solve(current_board=board)
print(extract[:, :, 0])
print(extract.shape)

[[10.  10.  10. ]
 [10.  -0.5 -0.5]
 [10.  -0.5 -0.5]]
(3, 3, 81)


In [54]:
def apply_heuristic(extract): 
    # return true if can apply, false if cannot apply
    out = []
    num_board = extract.shape[-1]
    for i in range(num_board): 
        ex = extract[:, :, i]
        out.append(np.unique(np.logical_or(ex == -0.5, ex == 10)).size == 1)
    out = np.array(out).astype(int)
    return out ^ 1

In [55]:
fil = apply_heuristic(extract)
len(fil)

81

In [63]:
rand_idx = np.random.randint(0, 82)
print(fil[rand_idx])
extract[:, :, rand_idx]

1


array([[-0.5, -0.5, -0.5],
       [-0.5, -0.5, -0.5],
       [ 0. ,  0. ,  0. ]])

In [ ]:
def solve(extract) : 
    num_board = extract.shape[-1]
    for i in range(num_board): 
        ex = extract[:, :, i]
        if (np.unique(np.logical_or(ex == -0.5, ex == 10)).size == 1) : 
            # no need to check for apply heuristic
            pass
        else : 
            # can check for apply heuristic
            if np.sum(ex < 0) == ex[1, 1]: 
                # can find safe cell
                pass
            else : 
                pass